language: go

sudo: false

go:
- '1.12'

script:
- ./.travis.gofmt.sh
- go test github.com/Wing924/ltsv -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)